name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - dev
      - feature/**
      - hotfix/**
  workflow_dispatch:
    inputs:
      release-type:
        description: 'What type of perform?'
        type: choice
        options:
          - no
          - yes
        default: no

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.release-type == 'yes'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for SonarCloud to analyze git history

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build and test with Maven
      run: mvn -B verify org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report

    - name: Analyze with SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      run: mvn -B sonar:sonar -Dsonar.projectKey=your-project-key -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io
