name: Terragrunt Plan

on:
  push:
    branches:
      - '**'
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      release-type:
        description: 'What type of perform?'
        type: choice
        options:
          - init
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          TERRAFORM_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
          wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAFORM_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Run Terragrunt Plan
        working-directory: terraform/devops/nonprod/us-east-1
        run: |
          terragrunt run-all plan

      - name: Run Terragrunt Apply
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.event.inputs.release-type == 'apply' }}
        working-directory: terraform/devops/nonprod/us-east-1
        run: |
          terragrunt run-all apply --auto-approve
