# name: Terragrunt Destroy on PR Close

# on:
#   pull_request:
#     types:
#       - closed
#     paths:
#       - 'terraform/**'

# jobs:
#   destroy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.8
#           terraform_wrapper: false

#       - name: Install Terragrunt
#         run: |
#           TERRAFORM_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
#           wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAFORM_VERSION}/terragrunt_linux_amd64
#           chmod +x terragrunt
#           sudo mv terragrunt /usr/local/bin/

#       - name: Run Terragrunt Destroy
#         working-directory: terraform/devops/nonprod/us-east-1
#         run: |
#           terragrunt run-all destroy --auto-approve